RAW_DIRECTORY_TWITTER = 'data/split/twitter'
RAW_DIRECTORY_MASTODON= 'data/split/mastodon'
PREPROCESSED_DIRECTORY_MASTODON= 'data/preprocessed/mastodon'
PREPROCESSED_DIRECTORY_TWITTER= 'data/preprocessed/twitter'
PREPROCESSED_DIRECTORY = 'data/preprocessed'
NORMALIZED_DIRECTORY = 'data/normalized'
FREQUENCIES_DIRECTORY = 'data/frequencies'
HEDOMETER_LEXICON = 'data/hedometer/polarizing_words.csv'
COMMON_WORDS = 'data/hedometer/count_1w.txt'
MISSPELLINGS_FILE = 'resources/Test_Set_3802_Pairs.txt'
EMOTICONS_FILE = 'resources/emoticons.csv'
SPACY_MODEL = 'en_core_web_sm'
WIKIDATA_API_URL = 'https://www.wikidata.org/w/api.php?action=wbsearchentities&language=en&format=json&search='
WIKIDATA_GET_API = 'https://www.wikidata.org/w/api.php?action=wbgetentities&sites=enwiki&languages=en&format=json&ids='
NUM_CLUSTERS = 150
ROUNDING_TIME = 60 #1 day