RAW_DIRECTORY_TWITTER = 'data/split/twitter'
RAW_DIRECTORY_MASTODON= 'data/split/mastodon'
PREPROCESSED_DIRECTORY_MASTODON= 'data/preprocessed/mastodon'
PREPROCESSED_DIRECTORY_TWITTER= 'data/preprocessed/twitter'
PREPROCESSED_DIRECTORY = 'data/preprocessed'
NORMALIZED_DIRECTORY = 'data/normalized'
FREQUENCIES_DIRECTORY = 'data/frequencies'
SPACY_MODEL = 'en_core_web_sm'
WIKIDATA_API_URL = 'https://www.wikidata.org/w/api.php?action=wbsearchentities&language=en&format=json&search='
WIKIDATA_GET_API = 'https://www.wikidata.org/w/api.php?action=wbgetentities&sites=enwiki&languages=en&format=json&ids='